### ISSUE TITLE
Non-Ascii Names

### ISSUE THREAD

**Issue by UnsignedByte** [Orbiit/elimination#16]
Users should be limited to ascii when inputting their full name, their email, names of games and descriptions of games.
[This user](https://orbiit.github.io/elimination/?@testtest) and [the game it participates in](https://orbiit.github.io/elimination/?!4a282) are extremely annoying to navigate in.

**Comment by SheepTester** [comment]
It's fine; you're supposed to use your real name anyways, and it'd be best if it allowed all unicode characters in case someone's name uses accents, for example
