### ISSUE TITLE
Add sign out button on homepage.

### ISSUE THREAD

**Issue by UnsignedByte** [Orbiit/elimination#17]
Sign out is currently possible through settings, but as the profile button no longer takes the user to settings, it takes a minimum of 3 clicks to sign out. This is unacceptable and as such there should be a sign out button on the home page of the website.

**Comment by SheepTester** [comment]
The normal user wouldn't need to sign out very often, and putting it on the home page makes users prone to accidentally signing out. There also is insufficient space in the header on mobile on the home page
