### ISSUE TITLE
Add rules button on homepage

### ISSUE THREAD

**Issue by UnsignedByte** [Orbiit/elimination#4]
Add a hyperlink to https://docs.google.com/document/d/1OQ4UDWlmrg4H5dfhgyShDEKfM7rjM8_Q5-Kk3MhAQTw/edit?usp=sharing
somewhere on the homepage

Makes it easier for any student to find and read the rules

**Comment by SheepTester** [comment]
I didn't intend this to be only for Gunn though, so idk

**Comment by SheepTester** [comment]
Also exists on the game page, so not necessary
