### ISSUE TITLE
Add button to see just the leaderboard per each game on one's homepage

### ISSUE THREAD

**Issue by heaucques** [Orbiit/elimination#5]
sure i can see my passphrase and who i need to stab but i also want to see who's stabbed the most nerds

**Comment by heaucques** [comment]
Also there should probably be a button to send you to the page of the game as well

**Comment by heaucques** [comment]
oh there is a button but its just in really light text
still there should be a dedicated leaderboard page

**Comment by SheepTester** [comment]
Leaderboard is the game page

> oh there is a button but its just in really light text

Then how should the design be improved?

**Comment by SheepTester** [comment]
@Velosify

**Comment by SheepTester** [comment]
9b2dce3f1e0bde87d5b4d8de88ab767932f346da is an attempt to fix this
